import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/CreatoDisplay-Regular.otf",
  variable: "--font-geist-sans",
  weight: "900",
  //subsets: ["latin"],
});

const geistMono = localFont({
  src: "./fonts/CreatoDisplay-Bold.otf",
  variable: "--font-geist-mono",
  weight: "900",
 // subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
